
-- oracle: demonstrate inspect vector with few elements,
-- then try large vector

column vct_item_value format A20
column id             format 9999
column vct            format A70 wrap
column vect           format A70 wrap
column elem_nr        format 9999 

set echo on
drop table dv1 ; 

create table dv1 (
  id    number generated by default as identity primary key
, vct   vector(3)
) ;

insert into dv1 (vct) values ('[1,2,3]'), ('[4,5,6]'), ('[1,1,1]');

select id, vct from dv1 ; 

set echo off
! read -p "Check the Vectors, Victor..." abc
set echo on

-- hand regex a varchar2, with CSV-values, then split it
with vctr as (
  select id, vct as csvlist from dv1
)
  select distinct /* i know, i know, distinct ?? */
         id
       , level as elem_nr
       , regexp_substr (
           csvlist,
           '[^,]+',
           1,
           level
         ) as vct_item_value
  from   vctr
  connect by level <=
    length ( trim ( both ',' from csvlist ) ) -
    length ( replace ( csvlist, ',' ) ) + 1
  order by id, level ;

set echo off
! read -p "Check the regex splitting of the vector-elements, Victor..." abc
set echo on

desc img_vector

select id, vect from img_vector where rownum < 3 ;

set echo off
! read -p "VECT is a VECTOR(512, FLOAT64), at some point vect will fail to display..." abc
set echo on

with vctr as (
  select id, vect as csvlist from img_vector
)
  select distinct 
         id
       , level as elem_nr
       , regexp_substr (
           csvlist,
           '[^,]+',
           1,
           level
         ) as vct_item_value
  from   vctr
  connect by level <=
    length ( trim ( both ',' from csvlist ) ) -
    length ( replace ( csvlist, ',' ) ) + 1
  order by id, level ;

set echo off
! read -p "No luck with regex of the large vector, Victor..." abc
set echo on


column eucl_dist format 0.99999
column  cos_dist format 0.99999

SELECT id  
, vct
, vct <-> '[2,3,4]'  as eucl_dist
, vct <=> '[2,3,4]'  as cos_dist
FROM dv1 ORDER BY id ;


